go resouce server client - monofleet

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -89,10 +89,25 @@ jobs:
           key: ${{ env.PRIVATE_SSH_KEY }}
           envs: PRIVATE_SSH_KEY,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY
           script: |-
-            touch /home/ubuntu/deploy.sh
-            echo "${{ secrets.SERVER_DEPLOY }}" > /home/ubuntu/deploy.sh
-            chmod +x /home/ubuntu/deploy.sh
-            ./home/ubuntu/deploy.sh
+            REPO_DIR="/home/ubuntu/gomarket"
+            if [ -d "$REPO_DIR" ]; then
+              echo "Repository already exists. Performing git pull..."
+              cd $REPO_DIR
+              git pull 
+            else
+              echo "Repository not found. Cloning the repository..."
+              git clone https://github.com/eniolastyle/gomarket.git $REPO_DIR
+              cd $REPO_DIR
+            fi
+            cd goserver
+            touch .env
+            echo "${env.SERVER_ENV}" > .env
+            npm install
+            sudo pm2 delete goserver || true
+            pm2 start app.js --name goserver
+            sudo rm -rf /etc/nginx/sites-available/default
+            sudo cp default /etc/nginx/sites-available/ -r
+            sudo systemctl restart nginx
 
   goclient_launch:
     needs: [goinfra_launch, goserver_launch]
@@ -112,10 +127,27 @@ jobs:
           key: ${{ env.PRIVATE_SSH_KEY }}
           envs: PRIVATE_SSH_KEY,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY
           script: |
-            touch /home/ubuntu/deploy.sh
-            echo "${{ secrets.CLIENT_DEPLOY }}" > /home/ubuntu/deploy.sh
-            chmod +x /home/ubuntu/deploy.sh
-            ./home/ubuntu/deploy.sh
+            REPO_DIR="/home/ubuntu/gomarket"
+            if [ -d "$REPO_DIR" ]; then
+              echo "Repository already exists. Performing git pull..."
+              cd $REPO_DIR
+              git pull 
+            else
+              echo "Repository not found. Cloning the repository..."
+              git clone https://github.com/eniolastyle/gomarket.git $REPO_DIR
+              cd $REPO_DIR
+            fi
+            cd goclient
+            touch .env
+            echo REACT_APP_API_URL=http://"${{ needs.goinfra_launch.outputs.SERVER_PUBLIC_IP }}" > .env
+            npm install
+            rm -rf build || true
+            npm run build
+            sudo pm2 delete goclient || true
+            pm2 serve build/ 3000 -f --name "goclient" --spa
+            sudo rm -rf /etc/nginx/sites-available/default
+            sudo cp default /etc/nginx/sites-available/ -r
+            sudo systemctl restart nginx
 
   godestroy:
     runs-on: ubuntu-latest
